### PR TITLE
add schema to filenames

### PR DESCRIPTION
**Pull request by brucebotes**
A simple enhancement. Added schema to table names for easy differentiation when running multi-tenant sites. Especially with the apartment.gem where schemas are duplicated.

### CODE REVIEW

**Comment by ankane** [comment]
Thanks for the pull request @brucebotes. What if we only did this when the schema didn't match the one specified in the database connection?

**Comment by brucebotes** [comment]
Hi Andrew,

I suppose a case statement can be included. If the schema name is not
';public' then show the alternative schema name......

Something like that.

For my usage I will have many postgresql schema's - one per tenant.
Therefore I prefer to have the schema name as a default for each table.
That way I can track typical usage patterns.

It is your choice I suppose.

**Comment by bjegannathan-rpx** [comment]
+1

**Comment by bragboy** [comment]
@ankane - Any plans to merge this PR?

**Comment by brucebotes** [comment]
You are most welcome to merge the code! Please be aware that II did not test it against test scripts either.

**Comment by thotmx** [comment]
@brucebotes why do you add capistrano files?

**Comment by bjegannathan-rpx** [comment]
Thanks @ankane for merging this !

**Pull request closed without merging**
