### PR TITLE
option for killing queries

### PR DESCRIPTION
**Pull request by bheemreddy181**
Ability for users to enable / disable killing queries from UI

ref : https://github.com/ankane/pghero/issues/365

### CODE REVIEW

**Comment by bheemreddy181** [comment]
Tested this locally 

Before on Live Queries Page 
Screen Shot 2021-03-23 at 10 18 37 PM

After on Live Queries Page 
Screen Shot 2021-03-23 at 10 18 46 PM

**Comment by bheemreddy181** [comment]
@ankane Whenever you are free - can you help with failing tests I haven’t changed anything which affects that. Are they flaky or am I missing something?

**Comment by bheemreddy181** [comment]
@ankane Can i get some review on this ?

**Comment by bheemreddy181** [comment]
a quick review or feedback will be much appreciated.

**Comment by bheemreddy181** [comment]
@ankane can i get a review for this ?

**Comment by bheemreddy181** [comment]
@ankane Can i get a review for this? if this looks ok I can add some documentation around this

**Comment by ankane** [comment]
Hey @bheemreddy181, thanks for the PR. After thinking about it more, it's not something I'd like to add right now. Sorry for changing my mind on this.

**Comment by bheemreddy181** [comment]
Any specific reason for that ?

**Comment by ankane** [comment]
It's just not something I'd like to focus on/spend time on right now.

**Pull request closed without merging**
