### PR TITLE
Update link to PEV, add Depesz, add pgMustard

### PR DESCRIPTION
**Pull request by mchristofides**
Hey @ankane, awesome work with pghero over the years. I saw as part of v3 (https://github.com/ankane/pghero/issues/415) you were planning to update the link to the newer Postgres Explain Visualizer (https://github.com/ankane/pghero/pull/369).

I wondered if you'd be open to linking to a few tools there?

If so, I still see a lot of love for the tool by depesz, that works well with the same JSON format. Also, I run a tiny company that makes a paid alternative called pgMustard, which also accepts the same JSON format, and adds more in the way of performance advice. A few of our customers are happy pghero users, and have asked for/suggested adding a link.

Let me know if you'd be interested, but would prefer it to be implemented differently!

### CODE REVIEW

**Comment by ankane** [comment]
Hey @mchristofides, thanks for the PR. However, I think it's simpler to only have one link, and it's not something I'd like to make configurable right now.

**Comment by mchristofides** [comment]
@ankane no worries, thanks for getting back to me. Happy to help if you want to make it configurable in future.

**Comment by ankane** [comment]
Thanks, I've added it to the list of things to consider/revisit for PgHero 3 (don't have a timeline on it yet).

**Comment by ankane** [comment]
Hey @mchristofides, just fyi, added the ability to customize the url in PgHero 3.

```yaml
visualize_url: https://app.pgmustard.com
```

**Comment by mchristofides** [comment]
@ankane thats awesome, thank you, I’ll let my customers know!

**Pull request closed without merging**
