### PR TITLE
explain insufficient privilege error in UI

### PR DESCRIPTION
**Pull request by seanlinsley**
I'd have rather not made these changes inline, but there's no way to add the title attribute from CSS.

#14

untitled

### CODE REVIEW

**Comment by seanlinsley** [comment]
Let me know if there's something else you had in mind for the UI.

**Comment by ankane** [comment]
Thanks Sean.  I think an inline message would be easier for users to spot.

**Comment by seanlinsley** [comment]
Okay, updated it to look like this:

screen shot 2015-01-30 at 11 58 31 am

**Comment by ankane** [comment]
Thanks Sean!

**Comment by seanlinsley** [comment]
Happy to help :cat:

**Pull request merged**
