### PR TITLE
Fix CSP not allowing loading from asset host

### PR DESCRIPTION
**Pull request by ThibG**

### CODE REVIEW

**Comment by ankane** [comment]
Hey @ThibG, thanks for the PR! We should be able to use `asset_host` instead of `Rails.configuration.action_controller.asset_host`.

**Comment by ThibG** [comment]
Changed. However, looked at the docs, I realize `asset_host` is not necessarily a directly usable string, it may also be a string with a pattern (which is randomly expanded to 0-4 by Rails, so we should detect it and add all hosts), or a proc (which we probably can't automatically generate a CSP rule from). I will have a look into that.

**Comment by ankane** [comment]
Hey @ThibG, thanks for updating. I just realized that complexity is why this feature was previously reverted. See #297. I think it makes sense for developers to manually set the CSP in this case instead of trying to generate one.

**Comment by ThibG** [comment]
Alright. I think it makes sense to handle the most common cases (I doubt the proc call is used that much), but you make the final call.
Also thank you for the pointer on how to set the CSP from outside PgHero itself!

**Comment by ankane** [comment]
Going to leave it up to users for now, but may reconsider https://github.com/ankane/pghero/commit/d821e750df684b5139b775fadaf217efd7715083 at some point. Also added a note in the code (should have done that the first time): https://github.com/ankane/pghero/commit/74f73d32523cc51cc37495dc740636380d56ea6f.

Anyways, thanks for the PR 👍

**Pull request closed without merging**
