### PR TITLE
Use a ConnectionPool vs per thread connection.

### PR DESCRIPTION
**Pull request by gaffneyc**
We have run into issues using PgHero when a connection goes bad (e.g.
PG::ConnectionBad). Since PgHero stores the connection per thread, when
a connection goes bad it never recovers. In our case one request would
succeed and the next would fail.

By using a connection pool instead we are able to check out new
connections when one goes bad. Additionally it should reduce the number
of connections to the database since it will not need one per worker
thread.

I am not entirely happy with the implementation since we have to wrap every query in
`connection_pool.with_connection` but it's the best way given how the library is written
to ensure the connections are checked back into the pool. I have also verified that
`with_connection` can be nested and will return the same connection if called within
itself.

This should supersede #16.

### CODE REVIEW

**Comment by gaffneyc** [comment]
I'm pretty sure this was introduced in 044f0b93e29d3ab811bfe6294f0285c41b4df093 PgHero is now doing more to manage the connection. When calling `Connection.connection` Rails will check a connection out of the pool for the thread and Rails (as part of the middleware chain) will check it back in when the request is done.

Something that is possible here is that since it's storing a reference to the connection, Rails is returning the connection to the pool and another thread could get a reference to it causing two threads to be attempting to use the same connection which is causing it to go bad.

It may be enough to change `.connection` to return `Connection.connection` and let Rails handle checking it back in but if the methods on `PgHero` are being used outside of the normal Rails request scope then it's likely that connections will be leaked.

**Comment by ankane** [comment]
Hey Chris, great point.  Thanks for digging into this one.  What do you think of the commit above as an alternative approach?

**Comment by gaffneyc** [comment]
It looks like it should fix the issue we're seeing, we'll update to 1.0.1 today to make sure.

The only issue I have is that the implementation will call `establish_connection` in each thread. I'm not sure if there is an actual issue here.

Alternatively you could do:

```ruby
def connection
  unless Connection.connected?
    Connection.establish_connection(current_config["url"])
  end

  Connection.connection
end
```

**Comment by sudhirj** [comment]
Fixing this might also fix #56

**Comment by ankane** [comment]
Cleaning up issues. This should be fixed now.

**Pull request closed without merging**
