### PR TITLE
Show estimated bloat percentage

### PR DESCRIPTION
**Pull request by andyatkinson**
This change adds a `Percent` column and orders the results by this column in descending order. That way an administrator can focus on the indexes with the highest bloat percentage, and work their way down to the less bloated indexes.

PgHero___Index_Bloat

Compare the bloat bytes to the total index bytes, as a percentage. Order
the index bloat by bloat percentage. These are the indexes that may
benefit the most from a reindex. Particularly if the indexes are on a
heavily written or queried table.

The associated tables may also require additional Autovacuum resources
directed towards their automatic vacuums, to make sure it is tuned
appropriately for the workload.

High bloat ratio may affect query planner index selection and index only scan query
performance.

References:

* https://medium.com/compass-true-north/dealing-with-significant-postgres-database-bloat-what-are-your-options-a6c1814a03a5
* https://www.cybertec-postgresql.com/en/detecting-table-bloat/

### CODE REVIEW

**Comment by andyatkinson** [comment]
The intention of this was to show a percentage and not bytes. Adding another commit.

**Comment by andyatkinson** [comment]
@ankane Thoughts on this relatively minor change (same SQL query was used, this just uses an additional field selected as part of an existing CTE)? I realize this page is hidden by default, you'd shared with me earlier it's accessible at `/pghero/index_bloat`. This adds a column that displays the index bloat bytes as a percentage of the total index bytes. The reason this was useful for us was that we could more easily focus on highest bloat first, and generally focus on addressing bloat that was 50% or higher, including eliminating it with a rebuild or repack, and then looking at the table level tuning, AV etc. that may have caused the higher bloat in the first place (more challenging and deeper problem).

**Comment by ankane** [comment]
Hey @andyatkinson, thanks for another PR. However, since the page is unlisted, I don't really want to do any work on it.

**Comment by andyatkinson** [comment]
@ankane Besides showing the bloat bytes as a percentage, which I think is easier to digest, and easier to order by worst offenders, having bloat > 20 or 30% could indicate an under-provisioned Autovacuum.

We've been experimenting with tuning the cost delay, and cost limit. It is also commonly recommended to tune the scale factor and threshold values. The idea would be that if the trigger conditions are 20% of dead rows trigger AV, then the bloat should be around 20% or less all of the time. If bloat creeps up to 50% or more then AV is not keeping up.

So I could imagine a feature even to highlight rows and make a suggestion. Combined with when the table was last vacuumed, it could be that the suggestion is that the table needs to be vacuumed, or the AV tuning needs to change either for the whole DB, or just for that single table.

**Pull request closed without merging**
