### PR TITLE
Use I18n for dates and timestamps

### PR DESCRIPTION
**Pull request by krists**
Fixes: #299

### CODE REVIEW

**Comment by ankane** [comment]
Hey @krists, thanks for the PR, and sorry for the delay! I think `to_s(:short)` is a bit better. Also, we shouldn't need to add `i18n` as a dependency since the code path will only be run when Rails is available.

Time is shown in the JavaScript slider on the query stats page as well. I'll update it to be consistent with the Rails default for now, but with more work, it could also be localized.

**Comment by krists** [comment]
@ankane `to_s(:short)` does not have the desired behavior. Here is an example from Rails app that uses Latvian locale:
```ruby
[10] pry(main)> Time.now.to_s(:short)
=> "19 Apr 11:00"
[11] pry(main)> Time.now.to_s(:long)
=> "April 19, 2020 11:00"
[12] pry(main)> I18n.l Time.now
=> "19.04.2020 11:00"
[13] pry(main)> I18n.l Time.now, format: :short
=> "19.04.2020 11:00"
[14] pry(main)> I18n.l Time.now, format: :long
=> "2020. gada 19. Aprīlis, 11:00:56"
```

Use of `:default` or `:short` format would be best.

I have removed lines from gemspec that added i18n dependency.

**Comment by ankane** [comment]
My bad, I thought `to_s(:short)` localized for some reason.

Thanks for updating the PR and the idea in general! I switched to `format: :short` in https://github.com/ankane/pghero/commit/54b00ca2bb15cd33debc82487dc10a68568ed438 since it's more like the existing format.

**Comment by krists** [comment]
@ankane Thank you!

**Pull request merged**
