### PR TITLE
Update explain page Postgres Explain Visualizer link destination

### PR DESCRIPTION
**Pull request by PikachuEXE**
Old website no longer functional

New website based on https://github.com/dalibo/pev2

### CODE REVIEW

**Comment by ankane** [comment]
Hey @PikachuEXE, thanks for the PR. Can you explain more? The website seems to be working.

**Comment by PikachuEXE** [comment]
Oh the existing one does not load when I submitted the PR
Maybe I can change this PR to add a link to https://explain.dalibo.com so people can use both?

**Comment by ankane** [comment]
Hey @PikachuEXE, we can switch the link for PgHero 3. I've added it the plan: #318

**Comment by twe4ked** [comment]
Here's another option I've been playing with recently:

https://explain.tensor.ru/

**Comment by ankane** [comment]
Hey @PikachuEXE, I decided to keep the current url for PgHero 3 (since it only stores queries in local storage), but added an option to allow users to change it in the config:

```yaml
visualize_url: https://explain.dalibo.com
```

**Comment by PikachuEXE** [comment]
I agree 
I only know they are sending data to remote server recently (it wasn't before)

**Comment by ankane** [comment]
Yeah, looks like it was changed in July.

**Pull request closed without merging**
