### PR TITLE
Lets pass query to explain as hidden field of form instead of query param. Query param has limitations for size.

### PR DESCRIPTION
**Pull request by oivoodoo**
Hello.

In case of having complex queries to explain it could paste the wrong query on render explain form because the query param has the limitations. It's better to make post with query as form param.

### CODE REVIEW

**Comment by ankane** [comment]
Hi Alexandr, thanks for the PR! This is great, but it looks like the params option only works with Rails 4.1 and above. Can you update to make it backward compatible with earlier versions?

**Comment by oivoodoo** [comment]
@ankane oh. I think you are right about it. I will try to make this change for earlier versions as well. thanks.

**Comment by oivoodoo** [comment]
@ankane I did test testing on Rails 3/4/5. and it looks like working fine now.

**Comment by ankane** [comment]
Thanks @oivoodoo. I'm worried this approach is a bit overcomplicated. How about using a conditional for rendering the button?

**Comment by oivoodoo** [comment]
@ankane do you mean something like that: ?

```
if Rails::VERSION::MAJOR >= 4
   button_to(name, url, html_options)
elsif Rails::VERSION::MAJOR == 3
    # implementation of `pghero_post_to` method that I proposed in this pull request
end
```

I've just done the simplified version without having conditions. it's working fine for Rails 3/4/5 because of using the same API for `form_tag` and `hidden_field_tag` as all rails version has.

**Comment by ankane** [comment]
@oivoodoo I was thinking:

```ruby
if Rails.version >= "4.1"
  # new button code
else
  # old button code
end
```

**Comment by oivoodoo** [comment]
But the old button code has no params to render as hidden field. It would
be still the same code to render form>button + hidden field.

**Comment by ankane** [comment]
Sorry, old and new button code weren't the clearest terms to use.

I was thinking we could keep the existing method (the one from the latest release) for Rails below 4.1, and use the params approach for 4.1+.

We could also add a form to directly to the view if you'd like to fix the issue below 4.1.  The current implementation adds a bit more complexity than is needed.

**Comment by oivoodoo** [comment]
@ankane I am ok with having view partial for rendering the button `Explain`. I will apply the new example today :)

**Comment by ankane** [comment]
Cleaning up PRs. Feel free to resubmit with the updates.

**Pull request closed without merging**
