### PR TITLE
Get correct information for versions newer than 9.5.0

### PR DESCRIPTION
**Pull request by thotmx**
* In PostgreSQL versions > 9.5.0, checkpoint_segments was removed.
  * It was replaced by: min_wal_size and max_wal_size
  * I've added the server version in the index, but it can be changed.

### CODE REVIEW

**Comment by ankane** [comment]
Thanks @thotmx, looks good.  I'd prefer to keep the server version off the index (just noise most of the time).  Also, let's wait until a release candidate of 9.6 before merging in the off chance something changes.

**Comment by thotmx** [comment]
You're right. Version number on index is not useful at all. I removed it.

**Comment by ankane** [comment]
Hey @thotmx, it looks like 9.6rc1 was released :) Also, a `server_version` method has been added since this PR was pushed. Can you update it when you have a chance?

**Comment by thotmx** [comment]
@ankane that's great. I'll work on that.

**Comment by thotmx** [comment]
@ankane I've tested it with my version for development of pghero_solo. It looks well.

I couldn't find the server_version method that you mentioned. Maybe the current way to get the version number would be more compatible with older versions.

**Comment by ankane** [comment]
Hey @thotmx, the `server_version` method is here: https://github.com/ankane/pghero/blob/master/lib/pghero/methods/query_stats.rb#L243

**Comment by thotmx** [comment]
Oh! I thought it was method or function for PostgreSQL. I'll use that!

**Comment by thotmx** [comment]
@ankane I think it's done. 
It's not the best code, but I think maybe if we need other extra options it would worth refactor it.

**Comment by ankane** [comment]
Would be great to clean it up before merging. I'd remove the extra method do something like:

```ruby
names =
  if server_version >= 90500
    %w(...)
  else
    %w(...)
  end
```

**Comment by thotmx** [comment]
@ankane Fair enough. Done!.

**Comment by ankane** [comment]
Awesome, thanks @thotmx! 💯  I just realized a few things that I should have earlier (doh!):

1. This applies to PostgreSQL 9.5, not 9.6 (hence no reason to wait for 9.6rc1)
2. The likely reason you added the DB version was because PgTune asks for it now

I've added the DB version here: b64ddb63217c1a5b84ca0cc701f5175a1bfd4056

**Pull request merged**
