### PR TITLE
Using permit instead of slice for Rails 5 compatibility

### PR DESCRIPTION
**Pull request by samuelgiles**
Rails 5 complains on the system view of unsafe parameters, this fixes that issue.

### CODE REVIEW

**Comment by ankane** [comment]
Thanks for the PR @samuelgiles 👍  Can we keep the original behavior for Rails below 5 for backward compatibility?

**Comment by samuelgiles** [comment]
'permit' works in Rails 4 too so it would only break compatibility with older versions.

The alternative that would work without the 'permit' method would be:
`
path_options = { :duration => params[:duration], :period => params[:period] }
`

**Comment by ankane** [comment]
@samuelgiles let's go with the 2nd approach. Users that have upgraded from Rails 3 may not be using strong parameters yet.

**Comment by ankane** [comment]
Hey @samuelgiles, I'd like to get a release out tonight, so I went ahead and pushed a fix. Thanks again for reporting this and submitting a PR 💯

**Comment by samuelgiles** [comment]
No problem! 👍

**Pull request closed without merging**
