### PR TITLE
Sequences NameSpace

### PR DESCRIPTION
**Pull request by efremropelato**
A sequences can be created in different schemas.
Methods::Sequence have to use this, not the table's schema.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @efremropelato, thanks for the PR 👍  Will try it out when I have some time. Can you remove the `.gitignore` update in the meantime?

**Comment by efremropelato** [comment]
Sure! 
I delete .gitignore update immediately.

**Comment by ankane** [comment]
Hey @efremropelato, I had to change one of the joins slightly to get it to work in my tests. See https://github.com/ankane/pghero/commit/2758a9f83f3b3d2532ccaf0b11145267aafea76a. Any idea why it worked for you without it?

**Comment by ankane** [comment]
Hey @efremropelato, I merged 2758a9f83f3b3d2532ccaf0b11145267aafea76a. Please let me know if it works for you.

**Comment by ankane** [comment]
This approach didn't cover quoted identifiers, so I rewrote the method here: https://github.com/ankane/pghero/blob/56ae896979fa6799b102f2c67bdafa719443e8fc/lib/pghero/methods/sequences.rb#L4

Should be much more maintainable going forward.

**Comment by efremropelato** [comment]
Now, It work in all my db!
Good work!
Thanks you

**Comment by ankane** [comment]
Big thanks for pointing out schema for sequence can be different than the table and adding the SQL to get correct schema 💯

**Pull request closed without merging**
